---
title: Bass Cycle
timezone: UTC
collections:
  mixes:
    title: Mixes
    output: false
  parties:
    title: Parties
    output: false
  posts:
    title: Posts
    output: true
  radio_shows:
    title: Radio Shows
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: index.html
    type: pages
  values:
    layout: homepage_layout
- scope:
    path: page
    type: pages
  values:
    layout: default
    showInNav: true
email: ollythedeveloper@gmail.com
description: Bass Cycle | London-based party crew
baseurl: 
url: 
github_username: Ronald-Crosby
plugins:
- jekyll-feed
- jekyll-postcss
collections_dir: content
exclude:
- Gemfile
- Gemfile.lock
- gulpfile.babel.js
- LICENSE.md
- node_modules
- package.json
- package-lock.json
- README.md
- src
- tailwind.config.js
